# Generated by Django 4.1.5 on 2023-01-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postal_code", models.CharField(default="59650-000", max_length=8)),
                ("street", models.TextField(blank=True)),
                ("district", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
