# Generated by Django 4.1.5 on 2023-01-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "ANUAL"),
                            ("T", "TRIMESTRAL"),
                            ("M", "MENSAL"),
                            ("D", "DIÁRIA"),
                            ("S", "SEMESTRAL"),
                        ],
                        max_length=1,
                    ),
                ),
                ("value_plan", models.FloatField()),
                (
                    "sport",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Plan",
                        to="sports.sport",
                    ),
                ),
            ],
        ),
    ]
